doctrine:
    dbal:
        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                MATCH_AGAINST: App\Extensions\Doctrine\MatchAgainst
                ST_Distance: App\Extensions\Doctrine\STDistance
                ST_GeomFromText: App\Extensions\Doctrine\STGeomFromText
                ST_Point: App\Extensions\Doctrine\STPoint