exercise_html_purifier:
    # full configuration reference: http://htmlpurifier.org/live/configdoc/plain.html
    html_profiles:
        default:
            config:
                # the charset used by the original contents
                Core.Encoding: 'UTF-8'
                Cache:
                    SerializerPermissions: null
                Filter:
                    YouTube: true
                HTML:
                    SafeIframe: true
                URI:
                    SafeIframeRegexp: '#^(https?:)?//(www\.youtube(?:-nocookie)?\.com/embed/|player\.vimeo\.com/video/)#'
        onlybr:
            config:
                HTML.Allowed:
                    br
        comment:
            config:
                HTML.Allowed:
                    br
        artistContent:
            config:
                HTML.Allowed:
                    br
        message:
            config:
                HTML.Allowed:
                    br
        lastMessage:
            config:
                HTML.Allowed:
                    ''