framework:
    html_sanitizer:
        sanitizers:
            default:
                allow_safe_elements: false
                allow_static_elements: false
            app.onlybr_sanitizer:
                allow_safe_elements: false
                allow_static_elements: false
                allow_elements:
                    br: [ ]
            app.publication_sanitizer:
                allow_elements:
                    div: ['class']
                    span: ['class']
                    a: ['href']
                    blockquote: []
                    br: []
                    em: []
                    h2: []
                    h3: []
                    p: []
                    strong: []
                    hr: []
                    dd: []
                    dl: []
                    dt: []
                    li: []
                    ol: []
                    ul: []
                    img: ['src']
                    iframe: ['class', 'src', 'frameborder', 'allow', 'allowfullscreen' ]

                allowed_media_hosts: ['musicall.com', 'youtube.com']
                allowed_media_schemes: ['http', 'https', 'mailto']
                allowed_link_schemes: ['http', 'https']

when@dev:
    framework:
        html_sanitizer:
            sanitizers:
                app.publication_sanitizer:
                    allowed_media_hosts: [ 'musicall.com', 'youtube.com', '127.0.0.1:8000', '127.0.0.1' ]
                    allowed_media_schemes: ['http', 'https', 'mailto']
