html_sanitizer:
    default_sanitizer: 'default'
    sanitizers:
        default:
            # Read https://github.com/tgalopin/html-sanitizer/blob/master/docs/1-getting-started.md#extensions
            # to learn more about which extensions you would like to enable.
            extensions: []
                # - 'basic'
                # - 'list'
                # - 'table'
                # - 'image'
                # - 'code'
                # - 'iframe'
                # - 'details'
                # - 'extra'
            # Read https://github.com/tgalopin/html-sanitizer/blob/master/docs/3-configuration-reference.md
            # to discover all the available options for each extension.
        only-br:
            extensions: ['only-br']
        publications-sanitizer:
            extensions:
                - publication
            tags:
                div:
                    allowed_attributes: ['class']
                span:
                    allowed_attributes: ['class']
                iframe:
                    allowed_hosts: ['youtube.com']
                    allowed_attributes: ['class', 'src', 'frameborder', 'allow', 'allowfullscreen']
