framework:
    http_client:
        scoped_clients:
            openai.client:
                base_uri: 'https://api.openai.com/'
                headers:
                    Content-Type: 'application/json'
                    Authorization: 'Bearer %env(OPEN_AI_KEY)%'