framework:
    rate_limiter:
        contact_form:
            policy: sliding_window
            limit: 3
            interval: '1 hour'
            cache_pool: "rate_limiter.cache"
        musician_search:
            policy: sliding_window
            limit: 10
            interval: '20 minutes'
            cache_pool: "rate_limiter.cache"
        registration:
            policy: fixed_window
            limit: 3
            interval: '1 hour'
            cache_pool: "rate_limiter.cache"
        message_send:
            policy: fixed_window
            limit: 20
            interval: '1 minute'
            cache_pool: "rate_limiter.cache"
        thread_creation:
            policy: fixed_window
            limit: 5
            interval: '1 minute'
            cache_pool: "rate_limiter.cache"
        comment_post:
            policy: fixed_window
            limit: 5
            interval: '2 minutes'
            cache_pool: "rate_limiter.cache"
        forum_topic_creation:
            policy: fixed_window
            limit: 1
            interval: '5 minutes'
            cache_pool: "rate_limiter.cache"
        forum_reply:
            policy: fixed_window
            limit: 1
            interval: '30 seconds'
            cache_pool: "rate_limiter.cache"
        musician_announce:
            policy: fixed_window
            limit: 1
            interval: '5 minutes'
            cache_pool: "rate_limiter.cache"
        musician_announce_daily:
            policy: fixed_window
            limit: 5
            interval: '1 day'
            cache_pool: "rate_limiter.cache"
        password_reset:
            policy: fixed_window
            limit: 4
            interval: '1 hour'
            cache_pool: "rate_limiter.cache"
        band_space_invitation:
            policy: fixed_window
            limit: 10
            interval: '1 hour'
            cache_pool: "rate_limiter.cache"
