services:
  webserver:
    image: nginx:stable
    container_name: musicall-webserver
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8080:8080"
    restart: always
    volumes:
      - $PWD:/var/www/musicall/
      - ./volumes/nginx/conf:/etc/nginx/conf.d
    networks:
      musicall:
        ipv4_address: 10.200.200.2

  php-fpm:
    build: .docker/fpm
    # image: musicall-fpm
    container_name: php-fpm
    working_dir: /var/www/musicall
    volumes:
      - ./volumes/php-fpm:/var/log/php:cached
      - $PWD:/var/www/musicall:cached
      - ./.docker/fpm/99-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini
    networks:
      musicall:
        ipv4_address: 10.200.200.3

  node:
    image: node:20
    container_name: node
    command: /bin/true
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
    networks:
      musicall:
        ipv4_address: 10.200.200.4

  php-musicall:
    build: .docker/cli-musicall
    # image: php-musicall
    container_name: php-musicall
    working_dir: /var/www
    command: /bin/true
    networks:
      musicall:
        ipv4_address: 10.200.200.5
    volumes:
      - .:/var/www:cached

  php-musicall-coverage:
    build: .docker/cli-musicall-coverage
    container_name: php-musicall-coverage
    working_dir: /var/www
    command: /bin/true
    networks:
      musicall:
        ipv4_address: 10.200.200.7
    volumes:
      - .:/var/www:cached

  db:
    image: mariadb:10.6
    container_name: musicall-db
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: musicall
    volumes:
      - db_files:/var/lib/mysql:cached
      - ./volumes/db/logs:/var/log/mysql:cached
    networks:
      musicall:
        ipv4_address: 10.200.200.6
        aliases:
          - db.musicall

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: musicall-es
    mem_limit: 512mb
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 10.200.200.1:9200:9200
      - 10.200.200.1:9300:9300
    networks:
      musicall:
        ipv4_address: 10.200.200.8
        aliases:
          - elasticsearch.musicall
    volumes:
      - es_files:/usr/share/elasticsearch/data:cached
networks:
  musicall:
    name: musicall
    ipam:
      driver: default
      config:
        - subnet: 10.200.200.0/26

volumes:
  db_files:
    driver: local
  es_files:
    driver: local
